spring.application.name=ecommerce-backend

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# JWT
jwt.secret=ecommerce-super-secret-key-that-is-at-least-256-bits-long-for-hs256-algorithm
jwt.expiration=86400000

# Logging
logging.level.com.ecommerce=INFO
logging.level.org.springframework.security=WARN
